#!/usr/bin/env python3
"""GitPersona: a loopback-only Git identity manager. Python 3.10+, Git and OpenSSH."""
from __future__ import annotations

import argparse
import contextlib
import json
import os
from pathlib import Path
import re
import secrets
import shlex
import shutil
import stat
import subprocess
import tempfile
import threading
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlsplit
import uuid

ROOT = Path(__file__).resolve().parent
FIELDS = ("user.name", "user.email", "core.sshCommand")
SIGNING_FIELDS = ("gpg.format", "user.signingkey", "commit.gpgsign")
KEY_HEADERS = (b"-----BEGIN OPENSSH PRIVATE KEY-----", b"-----BEGIN RSA PRIVATE KEY-----",
               b"-----BEGIN EC PRIVATE KEY-----", b"-----BEGIN DSA PRIVATE KEY-----",
               b"-----BEGIN PRIVATE KEY-----", b"-----BEGIN ENCRYPTED PRIVATE KEY-----")
SSH_CONFIG_BEGIN = "# >>> github-operator managed accounts >>>"
SSH_CONFIG_END = "# <<< github-operator managed accounts <<<"


class AppError(Exception):
    pass


def run(args, **kwargs):
    try:
        return subprocess.run(args, capture_output=True, text=True, timeout=12, **kwargs)
    except subprocess.TimeoutExpired as exc:
        raise AppError("The command timed out. Please try again.") from exc


def atomic_json(path, value):
    path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    fd, name = tempfile.mkstemp(dir=path.parent, prefix=".profiles-")
    try:
        with os.fdopen(fd, "w") as stream:
            json.dump(value, stream, indent=2)
            stream.write("\n")
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(name, path)
    finally:
        Path(name).unlink(missing_ok=True)


class Operator:
    def __init__(self, data_dir, home=None, env=None):
        self.home = Path(home or Path.home()).resolve()
        self.data_dir = Path(data_dir).resolve()
        self.env = dict(os.environ if env is None else env)
        self.lock = threading.RLock()
        self.profile_file = self.data_dir / "profiles.json"

    def git(self, *args):
        return run(["git", "-C", str(self.home), "config", *args], env=self.env)

    def read_profiles(self):
        if not self.profile_file.exists():
            return []
        try:
            data = json.loads(self.profile_file.read_text())
            if not isinstance(data, list) or any(not isinstance(p, dict) or
                not all(isinstance(p.get(k), str) for k in ("id", "label", "name", "email", "key")) or
                ("host" in p and not isinstance(p["host"], str)) or
                ("signing" in p and not isinstance(p["signing"], bool)) for p in data):
                raise ValueError()
            return data
        except (ValueError, OSError) as exc:
            raise AppError("Saved accounts could not be read. Check profiles.json; it has not been overwritten.") from exc

    def key_path(self, value):
        if not isinstance(value, str) or not value.strip() or any(ord(c) < 32 for c in value):
            raise AppError("Choose a valid private SSH key path.")
        value = value.strip()
        path = self.home / value[2:] if value.startswith("~/") else Path(value)
        if not path.is_absolute():
            raise AppError("Use an absolute key path or a path starting with ~/.")
        return path.resolve()

    @staticmethod
    def host_slug(label):
        slug = re.sub(r"[^a-z0-9]+", "-", label.casefold()).strip("-")[:42]
        return "github-" + (slug or "account")

    def ensure_profile_hosts(self, profiles):
        used = set()
        changed = False
        for profile in profiles:
            host = profile.get("host", "")
            if not re.fullmatch(r"github-[a-z0-9](?:[a-z0-9-]{0,48}[a-z0-9])?", host) or host in used:
                base = self.host_slug(profile["label"])
                host = base
                suffix = 2
                while host in used:
                    host = f"{base[:45]}-{suffix}"
                    suffix += 1
                profile["host"] = host
                changed = True
            used.add(host)
        return changed

    @staticmethod
    def ssh_config_quote(value):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'

    def managed_ssh_config(self, profiles):
        lines = [SSH_CONFIG_BEGIN, "# Generated by GitPersona. Edit accounts in the app."]
        for profile in profiles:
            lines.extend((
                f"Host {profile['host']}",
                "    HostName github.com",
                "    HostKeyAlias github.com",
                "    User git",
                f"    IdentityFile {self.ssh_config_quote(profile['key'])}",
                "    IdentitiesOnly yes",
                "",
            ))
        lines.append(SSH_CONFIG_END)
        return "\n".join(lines) + "\n"

    def sync_ssh_config(self, profiles):
        directory = self.home / ".ssh"
        config_link = directory / "config"
        if not profiles and not config_link.exists() and not config_link.is_symlink():
            return None
        directory.mkdir(parents=True, exist_ok=True, mode=0o700)
        target = config_link.resolve(strict=False) if config_link.is_symlink() else config_link
        target.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
        try:
            original = target.read_text() if target.exists() else ""
        except (OSError, UnicodeError) as exc:
            raise AppError("Your SSH config could not be read, so account aliases were not changed.") from exc
        begin_count = original.count(SSH_CONFIG_BEGIN)
        end_count = original.count(SSH_CONFIG_END)
        if begin_count != end_count or begin_count > 1:
            raise AppError("The GitPersona block in ~/.ssh/config is incomplete or duplicated. Fix its markers before saving accounts.")
        pattern = re.compile(re.escape(SSH_CONFIG_BEGIN) + r".*?" + re.escape(SSH_CONFIG_END) + r"\n?", re.DOTALL)
        unmanaged = pattern.sub("", original).lstrip("\n")
        managed = self.managed_ssh_config(profiles) if profiles else ""
        rendered = managed + ("\n" if managed and unmanaged else "") + unmanaged
        if rendered == original:
            return None
        lock = Path(str(target) + ".github-operator.lock")
        try:
            lock_fd = os.open(lock, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
        except FileExistsError as exc:
            raise AppError("SSH configuration is locked by another GitPersona process. Try again shortly.") from exc
        os.close(lock_fd)
        stage = None
        try:
            mode = stat.S_IMODE(target.stat().st_mode) if target.exists() else 0o600
            backup_dir = self.data_dir / "backups"
            backup_dir.mkdir(parents=True, exist_ok=True, mode=0o700)
            backup = backup_dir / f"ssh-config-{time.time_ns()}"
            backup_fd = os.open(backup, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
            with os.fdopen(backup_fd, "w") as stream:
                stream.write(original)
            fd, name = tempfile.mkstemp(prefix=".github-operator-ssh-", dir=target.parent)
            stage = Path(name)
            with os.fdopen(fd, "w") as stream:
                stream.write(rendered)
                stream.flush()
                os.fsync(stream.fileno())
            os.chmod(stage, mode)
            os.replace(stage, target)
            return str(backup)
        finally:
            if stage:
                stage.unlink(missing_ok=True)
            lock.unlink(missing_ok=True)

    def prepare_origins(self):
        with self.lock:
            profiles = self.read_profiles()
            changed = self.ensure_profile_hosts(profiles)
            self.sync_ssh_config(profiles)
            if changed:
                atomic_json(self.profile_file, profiles)

    def validate_key(self, path):
        try:
            if not path.is_file():
                raise AppError("The private key does not exist at that path.")
            with path.open("rb") as stream:
                header = stream.readline(100).strip()
            if header not in KEY_HEADERS:
                raise AppError("Select a private SSH key, not a .pub file or SSH configuration.")
            if path.stat().st_mode & 0o077:
                raise AppError("This private key is accessible to other users. Run chmod 600 on it first.")
        except OSError as exc:
            raise AppError("The private SSH key is not readable.") from exc

    def key_info(self, path):
        info = {"path": str(path), "filename": path.name, "available": False,
                "fingerprint": None, "algorithm": None, "public_key": None, "error": None}
        try:
            self.validate_key(path)
            info["available"] = True
        except AppError as exc:
            info["error"] = str(exc)
        pub = Path(str(path) + ".pub")
        if pub.is_file() and pub.stat().st_size < 32768:
            try:
                public_text = pub.read_text().strip()
            except (OSError, UnicodeError):
                public_text = ""
            # ssh-keygen -lf accepts private keys too; never expose one mislabeled .pub.
            if re.fullmatch(r"(?:ssh-[\w-]+|ecdsa-[\w-]+|sk-[\w@.-]+) [A-Za-z0-9+/=]+(?: [^\r\n]*)?", public_text):
                result = run(["ssh-keygen", "-lf", str(pub)], env=self.env)
                if result.returncode == 0:
                    parts = result.stdout.strip().split()
                    info.update(fingerprint=parts[1], algorithm=parts[-1].strip("()"), public_key=public_text)
        return info

    def generate_key(self, data):
        with self.lock:
            filename = data.get("filename", "")
            email = data.get("email", "")
            passphrase = data.get("passphrase", "")
            if not isinstance(filename, str) or not re.fullmatch(r"id_[A-Za-z0-9][A-Za-z0-9_.-]{0,90}", filename) or filename.endswith(".pub"):
                raise AppError("Choose a filename beginning with id_, using only letters, numbers, dots, underscores, or hyphens. Do not add .pub.")
            if not isinstance(email, str) or len(email) > 200 or not re.fullmatch(r"[^\s@]+@[^\s@]+\.[^\s@]+", email) or any(ord(c) < 32 for c in email):
                raise AppError("Enter a valid email address for the key comment.")
            if not isinstance(passphrase, str) or any(ord(c) < 32 or ord(c) == 127 for c in passphrase) or len(passphrase.encode("utf-8")) > 512:
                raise AppError("Use a passphrase without control characters, up to 512 bytes.")
            if passphrase and len(passphrase) < 5:
                raise AppError("Use at least 5 characters for a passphrase, or leave it empty.")
            directory = self.home / ".ssh"
            directory.mkdir(parents=True, exist_ok=True, mode=0o700)
            target = directory / filename
            public_target = directory / (filename + ".pub")
            if os.path.lexists(target) or os.path.lexists(public_target):
                raise AppError("That key filename already exists. Choose a different name; existing keys are never overwritten.")
            with tempfile.TemporaryDirectory(prefix=".operator-key-", dir=directory) as staging:
                private = Path(staging) / "key"
                # A new session has no controlling terminal. OpenSSH reads the
                # two passphrase prompts from stdin, never command-line arguments.
                result = run(["ssh-keygen", "-q", "-t", "ed25519", "-f", str(private), "-C", email],
                             input=passphrase + "\n" + passphrase + "\n", start_new_session=True,
                             env={**self.env, "SSH_ASKPASS_REQUIRE": "never"})
                if result.returncode:
                    raise AppError("SSH key generation failed. Check the filename, passphrase, and SSH directory permissions.")
                public = Path(str(private) + ".pub")
                os.chmod(private, 0o600)
                os.chmod(public, 0o644)
                info = self.key_info(private)
                if not info["available"] or not info["public_key"]:
                    raise AppError("The generated key could not be validated. No key was installed.")
                installed_private = False
                try:
                    # Hard links publish each completed file without overwriting
                    # files created by another process after the initial check.
                    os.link(private, target)
                    installed_private = True
                    os.link(public, public_target)
                except OSError as exc:
                    if installed_private and target.exists() and os.path.samestat(target.stat(), private.stat()):
                        target.unlink()
                    if isinstance(exc, FileExistsError):
                        raise AppError("That key filename already exists. Choose a different name.") from exc
                    raise
                info.update(path=str(target.resolve()), filename=filename, encrypted=bool(passphrase))
                return info

    def discover_keys(self, profiles):
        paths = {Path(p["key"]) for p in profiles}
        directory = self.home / ".ssh"
        if directory.is_dir():
            for path in directory.iterdir():
                if not path.is_file() or path.suffix == ".pub":
                    continue
                try:
                    with path.open("rb") as stream:
                        if stream.readline(100).strip() in KEY_HEADERS:
                            paths.add(path.resolve())
                except OSError:
                    continue
        return [self.key_info(path) for path in sorted(paths)]

    @staticmethod
    def ssh_command(key):
        return "ssh -i " + shlex.quote(key) + " -o IdentitiesOnly=yes"

    def values(self, file=None):
        values = {}
        for key in FIELDS + SIGNING_FIELDS:
            scope = ["--file", str(file)] if file else ["--global"]
            result = self.git(*scope, "--includes", "--get", key)
            if result.returncode not in (0, 1):
                raise AppError("Git configuration could not be read: " + result.stderr.strip())
            values[key] = result.stdout.rstrip("\n") if result.returncode == 0 else None
        return values

    def status(self):
        with self.lock:
            profiles = self.read_profiles()
            self.ensure_profile_hosts(profiles)
            values = self.values()
            keys = self.discover_keys(profiles)
            for p in profiles:
                matches_core = (values.get("user.name") == p["name"] and
                                values.get("user.email") == p["email"] and
                                values.get("core.sshCommand") == self.ssh_command(p["key"]))
                if p.get("signing"):
                    pub_path = str(Path(p["key"] + ".pub").resolve())
                    matches_signing = (values.get("gpg.format") == "ssh" and
                                       values.get("user.signingkey") == pub_path and
                                       values.get("commit.gpgsign") == "true")
                    p["active"] = matches_core and matches_signing
                else:
                    p["active"] = matches_core
            warnings = []
            for key in ("GIT_SSH_COMMAND", "GIT_SSH", "GIT_AUTHOR_NAME", "GIT_AUTHOR_EMAIL",
                        "GIT_COMMITTER_NAME", "GIT_COMMITTER_EMAIL", "GIT_CONFIG_COUNT"):
                if key in self.env:
                    warnings.append(f"{key} is set in the server environment and may override these defaults.")
            return {"profiles": profiles, "keys": keys, "git": values, "warnings": warnings,
                    "home": str(self.home), "checked_at": int(time.time()), "config_path": str(self.config_path()),
                    "ssh_config_path": str((self.home / ".ssh/config").resolve(strict=False))}

    def save(self, data):
        with self.lock:
            cleaned = {}
            for field in ("label", "name", "email"):
                value = data.get(field)
                if not isinstance(value, str) or not value.strip() or len(value) > 200 or any(ord(c) < 32 for c in value):
                    raise AppError(f"Enter a valid {field} (up to 200 characters).")
                cleaned[field] = value.strip()
            if not re.fullmatch(r"[^\s@]+@[^\s@]+\.[^\s@]+", cleaned["email"]):
                raise AppError("Enter a valid Git email address.")
            path = self.key_path(data.get("key"))
            self.validate_key(path)
            cleaned["key"] = str(path)
            cleaned["signing"] = bool(data.get("signing", False))
            profiles = self.read_profiles()
            existing_id = data.get("id")
            existing = next((p for p in profiles if p["id"] == existing_id), None) if existing_id else None
            if existing_id and not existing:
                raise AppError("This account no longer exists. Refresh and try again.")
            cleaned["id"] = existing_id or uuid.uuid4().hex
            if existing and existing.get("host"):
                cleaned["host"] = existing["host"]
            if any(p["id"] != cleaned["id"] and p["label"].casefold() == cleaned["label"].casefold() for p in profiles):
                raise AppError("An account with that label already exists.")
            profiles = [cleaned if p["id"] == cleaned["id"] else p for p in profiles] if existing_id else profiles + [cleaned]
            self.ensure_profile_hosts(profiles)
            self.sync_ssh_config(profiles)
            atomic_json(self.profile_file, profiles)
            return cleaned

    def delete(self, profile_id):
        with self.lock:
            profiles = self.read_profiles()
            if not any(p["id"] == profile_id for p in profiles):
                raise AppError("Account not found.")
            remaining = [p for p in profiles if p["id"] != profile_id]
            self.ensure_profile_hosts(remaining)
            self.sync_ssh_config(remaining)
            atomic_json(self.profile_file, remaining)

    def config_path(self):
        if self.env.get("GIT_CONFIG_GLOBAL"):
            return Path(self.env["GIT_CONFIG_GLOBAL"]).expanduser().resolve()
        main = self.home / ".gitconfig"
        xdg = Path(self.env.get("XDG_CONFIG_HOME") or self.home / ".config") / "git/config"
        return (main if main.exists() or not xdg.exists() else xdg).resolve()

    def activate(self, profile_id):
        with self.lock:
            profiles = self.read_profiles()
            self.ensure_profile_hosts(profiles)
            self.sync_ssh_config(profiles)
            profile = next((p for p in profiles if p["id"] == profile_id), None)
            if not profile:
                raise AppError("Account not found.")
            self.validate_key(Path(profile["key"]))
            target = self.config_path()
            target.parent.mkdir(parents=True, exist_ok=True)
            lock = Path(str(target) + ".lock")
            try:
                fd = os.open(lock, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
            except FileExistsError as exc:
                raise AppError("Git configuration is locked by another process. Try again when it finishes.") from exc
            os.close(fd)
            stage = None
            try:
                original = target.read_bytes() if target.exists() else b""
                mode = stat.S_IMODE(target.stat().st_mode) if target.exists() else 0o600
                fd, filename = tempfile.mkstemp(prefix=".github-operator-", dir=target.parent)
                stage = Path(filename)
                with os.fdopen(fd, "wb") as stream:
                    stream.write(original)
                expected = dict(zip(FIELDS, (profile["name"], profile["email"], self.ssh_command(profile["key"]))))
                if profile.get("signing"):
                    pub = Path(profile["key"] + ".pub")
                    if not pub.is_file():
                        raise AppError(f"Public key {pub.name} is missing. Cannot activate SSH commit signing.")
                    expected["gpg.format"] = "ssh"
                    expected["user.signingkey"] = str(pub.resolve())
                    expected["commit.gpgsign"] = "true"
                for key, value in expected.items():
                    result = self.git("--file", str(stage), "--replace-all", key, value)
                    if result.returncode:
                        raise AppError("Git configuration could not be updated: " + result.stderr.strip())
                if not profile.get("signing") and self.values(stage).get("commit.gpgsign") == "true":
                    self.git("--file", str(stage), "--replace-all", "commit.gpgsign", "false")
                actual = self.values(stage)
                if any(actual.get(k) != v for k, v in expected.items()):
                    raise AppError("An included Git config overrides this identity. Adjust the included settings before switching.")
                # Preserve the exact previous file before the single atomic replacement.
                backup_dir = self.data_dir / "backups"
                backup_dir.mkdir(parents=True, exist_ok=True, mode=0o700)
                backup = backup_dir / f"global-{time.time_ns()}.gitconfig"
                backup_fd = os.open(backup, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
                with os.fdopen(backup_fd, "wb") as stream:
                    stream.write(original)
                os.chmod(stage, mode)
                with stage.open("rb") as stream:
                    os.fsync(stream.fileno())
                os.replace(stage, target)
                return {"label": profile["label"], "backup": str(backup)}
            finally:
                if stage:
                    stage.unlink(missing_ok=True)
                    Path(str(stage) + ".lock").unlink(missing_ok=True)
                lock.unlink(missing_ok=True)

    def verify_profile(self, profile_id):
        with self.lock:
            profiles = self.read_profiles()
            self.ensure_profile_hosts(profiles)
            self.sync_ssh_config(profiles)
            profile = next((p for p in profiles if p["id"] == profile_id), None)
            if not profile:
                raise AppError("Account not found.")
            self.validate_key(Path(profile["key"]))
            result = run([
                "ssh", "-T", "-o", "BatchMode=yes", "-o", "ConnectTimeout=8",
                "-o", "StrictHostKeyChecking=accept-new", f"git@{profile['host']}",
            ], env=self.env)
            output = (result.stdout + "\n" + result.stderr).strip()
            match = re.search(r"Hi ([A-Za-z0-9-]+)! You've successfully authenticated", output)
            if match:
                return {"ok": True, "username": match.group(1), "host": profile["host"],
                        "message": f"Authenticated to GitHub as {match.group(1)}."}
            if "Permission denied (publickey)" in output:
                raise AppError("GitHub rejected this key. Add its public key to the intended GitHub account, or unlock the key with ssh-add and try again.")
            if "Host key verification failed" in output:
                raise AppError("GitHub's host key could not be verified. Check ~/.ssh/known_hosts and try again.")
            if "Could not resolve hostname" in output:
                raise AppError("The account's SSH host alias could not be resolved. Resave the account to rebuild ~/.ssh/config.")
            if "timed out" in output.casefold() or "no route to host" in output.casefold():
                raise AppError("GitHub could not be reached. Check your network connection and try again.")
            detail = output.splitlines()[-1][:240] if output else f"SSH exited with status {result.returncode}."
            raise AppError("SSH verification failed: " + detail)

    def scan_repositories(self, custom_path=None):
        with self.lock:
            profiles = self.read_profiles()
            found_paths = []
            if custom_path:
                target = Path(custom_path).expanduser().resolve()
                if (target / ".git").exists():
                    found_paths.append(target)
                elif target.is_dir():
                    for root, dirs, _ in os.walk(target):
                        if ".git" in dirs:
                            found_paths.append(Path(root).resolve())
                            dirs.remove(".git")
                        if len(found_paths) >= 40:
                            break
            else:
                candidate_dirs = [
                    self.home / name for name in ("clients", "Projects", "myprojects", "src", "Work", "Documents", "github-operator")
                ]
                candidate_dirs.append(self.home)
                seen = set()
                for base in candidate_dirs:
                    if not base.is_dir():
                        continue
                    if (base / ".git").exists() and base != self.home:
                        if base not in seen:
                            seen.add(base)
                            found_paths.append(base)
                    try:
                        for entry in base.iterdir():
                            if entry.is_dir() and (entry / ".git").exists():
                                if entry not in seen:
                                    seen.add(entry)
                                    found_paths.append(entry)
                            elif entry.is_dir() and base != self.home:
                                try:
                                    for sub in entry.iterdir():
                                        if sub.is_dir() and (sub / ".git").exists():
                                            if sub not in seen:
                                                seen.add(sub)
                                                found_paths.append(sub)
                                except (OSError, PermissionError):
                                    continue
                    except (OSError, PermissionError):
                        continue
                    if len(found_paths) >= 40:
                        break

            repos = []
            for repo_path in sorted(found_paths):
                info = self.inspect_repository(repo_path, profiles)
                if info:
                    repos.append(info)
            return repos

    def inspect_repository(self, path, profiles=None):
        if profiles is None:
            profiles = self.read_profiles()
        p = Path(path).resolve()
        if not (p / ".git").exists():
            return None

        def local_get(key):
            res = run(["git", "-C", str(p), "config", "--local", "--get", key], env=self.env)
            return res.stdout.strip() if res.returncode == 0 else None

        name = local_get("user.name")
        email = local_get("user.email")
        ssh_cmd = local_get("core.sshCommand")
        gpg_sign = local_get("commit.gpgsign")
        origin_res = run(["git", "-C", str(p), "remote", "get-url", "origin"], env=self.env)
        origin = origin_res.stdout.strip() if origin_res.returncode == 0 else None
        branch_res = run(["git", "-C", str(p), "branch", "--show-current"], env=self.env)
        branch = branch_res.stdout.strip() if branch_res.returncode == 0 else ""

        is_pinned = bool(name and email)
        matched_profile = None
        if is_pinned:
            matched_profile = next((pr for pr in profiles if pr["name"] == name and pr["email"] == email), None)
        else:
            if origin:
                for pr in profiles:
                    if pr.get("host") and f"@{pr['host']}:" in origin:
                        matched_profile = pr
                        break

        short_path = str(p)
        if short_path.startswith(str(self.home)):
            short_path = "~" + short_path[len(str(self.home)):]

        return {
            "path": str(p),
            "short_path": short_path,
            "name": p.name,
            "branch": branch or "HEAD",
            "origin": origin,
            "local_name": name,
            "local_email": email,
            "local_ssh": ssh_cmd,
            "signing": gpg_sign == "true",
            "is_pinned": is_pinned,
            "matched_profile_id": matched_profile["id"] if matched_profile else None,
            "matched_profile_label": matched_profile["label"] if matched_profile else None,
        }

    def pin_repository(self, repo_path, profile_id, enable_signing=True):
        with self.lock:
            profiles = self.read_profiles()
            profile = next((pr for pr in profiles if pr["id"] == profile_id), None)
            if not profile:
                raise AppError("Account not found.")
            p = Path(repo_path).resolve()
            if not (p / ".git").exists():
                raise AppError("The specified directory is not a Git repository.")

            res = run(["git", "-C", str(p), "config", "--local", "user.name", profile["name"]], env=self.env)
            if res.returncode:
                raise AppError("Could not set local user.name.")
            res = run(["git", "-C", str(p), "config", "--local", "user.email", profile["email"]], env=self.env)
            if res.returncode:
                raise AppError("Could not set local user.email.")
            res = run(["git", "-C", str(p), "config", "--local", "core.sshCommand", self.ssh_command(profile["key"])], env=self.env)
            if res.returncode:
                raise AppError("Could not set local core.sshCommand.")
            pub = Path(profile["key"] + ".pub")
            if enable_signing and pub.is_file():
                run(["git", "-C", str(p), "config", "--local", "gpg.format", "ssh"], env=self.env)
                run(["git", "-C", str(p), "config", "--local", "user.signingkey", str(pub.resolve())], env=self.env)
                run(["git", "-C", str(p), "config", "--local", "commit.gpgsign", "true"], env=self.env)
            return self.inspect_repository(p, profiles)

    def unpin_repository(self, repo_path):
        with self.lock:
            p = Path(repo_path).resolve()
            if not (p / ".git").exists():
                raise AppError("The specified directory is not a Git repository.")
            for key in ("user.name", "user.email", "core.sshCommand", "gpg.format", "user.signingkey", "commit.gpgsign"):
                run(["git", "-C", str(p), "config", "--local", "--unset", key], env=self.env)
            return self.inspect_repository(p)

    def list_backups(self):
        backup_dir = self.data_dir / "backups"
        if not backup_dir.is_dir():
            return []
        items = []
        for file in sorted(backup_dir.iterdir(), key=lambda f: f.stat().st_mtime, reverse=True):
            if not file.is_file():
                continue
            name = file.name
            btype = "git" if name.startswith("global-") else ("ssh" if name.startswith("ssh-config-") else "unknown")
            try:
                content = file.read_text()[:400]
            except Exception:
                content = ""
            items.append({
                "id": name,
                "type": btype,
                "size": file.stat().st_size,
                "timestamp": int(file.stat().st_mtime),
                "preview": content,
            })
        return items

    def restore_backup(self, backup_id):
        with self.lock:
            if not re.fullmatch(r"[A-Za-z0-9_.-]+", backup_id):
                raise AppError("Invalid backup identifier.")
            source = self.data_dir / "backups" / backup_id
            if not source.is_file():
                raise AppError("Backup file does not exist.")
            content = source.read_bytes()
            backup_dir = self.data_dir / "backups"
            backup_dir.mkdir(parents=True, exist_ok=True, mode=0o700)
            if backup_id.startswith("global-"):
                target = self.config_path()
                if target.exists():
                    safety = backup_dir / f"global-{time.time_ns()}.gitconfig"
                    safety.write_bytes(target.read_bytes())
                    os.chmod(safety, 0o600)
                target.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
                fd, temp_path = tempfile.mkstemp(prefix=".gitpersona-restore-", dir=target.parent)
                with os.fdopen(fd, "wb") as f:
                    f.write(content)
                os.chmod(temp_path, 0o600)
                os.replace(temp_path, target)
                return {"restored": backup_id, "type": "git", "target": str(target)}
            elif backup_id.startswith("ssh-config-"):
                target = self.home / ".ssh" / "config"
                if target.exists():
                    safety = backup_dir / f"ssh-config-{time.time_ns()}"
                    safety.write_bytes(target.read_bytes())
                    os.chmod(safety, 0o600)
                target.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
                fd, temp_path = tempfile.mkstemp(prefix=".gitpersona-restore-", dir=target.parent)
                with os.fdopen(fd, "wb") as f:
                    f.write(content)
                os.chmod(temp_path, 0o600)
                os.replace(temp_path, target)
                return {"restored": backup_id, "type": "ssh", "target": str(target)}
            else:
                raise AppError("Unrecognized backup type.")


class Server(ThreadingHTTPServer):
    daemon_threads = True

    def __init__(self, address, operator):
        self.operator = operator
        self.token = secrets.token_urlsafe(32)
        self.operator.prepare_origins()
        super().__init__(address, Handler)


class Handler(BaseHTTPRequestHandler):
    def log_message(self, format, *args):
        pass

    def respond(self, code, value, content_type="application/json"):
        body = json.dumps(value).encode() if content_type == "application/json" else value
        self.send_response(code)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("X-Frame-Options", "DENY")
        self.send_header("Referrer-Policy", "no-referrer")
        self.send_header("Content-Security-Policy", "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'")
        self.end_headers()
        self.wfile.write(body)

    def trusted(self, mutation=False):
        port = self.server.server_port
        allowed_hosts = {f"127.0.0.1:{port}", f"localhost:{port}"}
        if self.headers.get("Host") not in allowed_hosts:
            self.respond(403, {"error": "Only local requests are allowed."})
            return False
        origin = self.headers.get("Origin")
        if origin and origin not in {f"http://{host}" for host in allowed_hosts}:
            self.respond(403, {"error": "Cross-origin requests are not allowed."})
            return False
        if self.headers.get("Sec-Fetch-Site") == "cross-site":
            self.respond(403, {"error": "Cross-site requests are not allowed."})
            return False
        if mutation and not secrets.compare_digest(self.headers.get("X-Operator-Token", ""), self.server.token):
            self.respond(403, {"error": "Refresh the page before changing an account."})
            return False
        return True

    def do_GET(self):
        if not self.trusted():
            return
        path = urlsplit(self.path).path
        try:
            if path == "/api/status":
                self.respond(200, {**self.server.operator.status(), "token": self.server.token})
            elif path == "/api/repos":
                self.respond(200, self.server.operator.scan_repositories())
            elif path == "/api/backups":
                self.respond(200, self.server.operator.list_backups())
            elif path in ("/", "/app.js", "/style.css", "/favicon.svg"):
                filename, mime = {"/": ("index.html", "text/html; charset=utf-8"),
                    "/app.js": ("app.js", "text/javascript; charset=utf-8"),
                    "/style.css": ("style.css", "text/css; charset=utf-8"),
                    "/favicon.svg": ("favicon.svg", "image/svg+xml")}[path]
                self.respond(200, (ROOT / "static" / filename).read_bytes(), mime)
            else:
                self.respond(404, {"error": "Not found."})
        except (AppError, OSError) as exc:
            self.respond(500, {"error": str(exc)})

    def do_POST(self):
        if not self.trusted(mutation=True):
            return
        try:
            size = int(self.headers.get("Content-Length", "0"))
            if size < 1 or size > 16384 or self.headers.get("Content-Type", "").split(";")[0] != "application/json":
                raise AppError("Send a small JSON request.")
            data = json.loads(self.rfile.read(size))
            if not isinstance(data, dict):
                raise AppError("Invalid request.")
            path = urlsplit(self.path).path
            if path == "/api/profiles/save":
                result = self.server.operator.save(data)
            elif path == "/api/keys/generate":
                result = self.server.operator.generate_key(data)
            elif path == "/api/profiles/activate":
                result = self.server.operator.activate(data.get("id"))
            elif path == "/api/profiles/verify":
                result = self.server.operator.verify_profile(data.get("id"))
            elif path == "/api/profiles/delete":
                self.server.operator.delete(data.get("id"))
                result = {"ok": True}
            elif path == "/api/repos/scan":
                result = self.server.operator.scan_repositories(data.get("path"))
            elif path == "/api/repos/pin":
                result = self.server.operator.pin_repository(data.get("path"), data.get("profile_id"), data.get("signing", True))
            elif path == "/api/repos/unpin":
                result = self.server.operator.unpin_repository(data.get("path"))
            elif path == "/api/backups/restore":
                result = self.server.operator.restore_backup(data.get("id"))
            else:
                self.respond(404, {"error": "Not found."})
                return
            self.respond(200, result)
        except (ValueError, AppError) as exc:
            self.respond(400, {"error": str(exc)})
        except OSError as exc:
            self.respond(500, {"error": "The change could not be saved: " + str(exc)})


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--port", type=int, default=7463)
    parser.add_argument("--data-dir", type=Path, default=ROOT / ".data")
    parser.add_argument("--open", action="store_true", help="Open GitPersona in your default browser on start")
    args = parser.parse_args()
    for command in ("git", "ssh", "ssh-keygen"):
        if not shutil.which(command):
            parser.error(f"{command} must be installed.")
    server = Server(("127.0.0.1", args.port), Operator(args.data_dir))
    url = f"http://127.0.0.1:{server.server_port}"
    print(f"GitPersona is ready at {url}", flush=True)
    if args.open:
        import webbrowser
        threading.Timer(0.3, lambda: webbrowser.open(url)).start()
    with contextlib.suppress(KeyboardInterrupt):
        server.serve_forever()
    server.server_close()


if __name__ == "__main__":
    main()
